/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "FramewinDLG.h"
#include <string.h>
#include <stdio.h>
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_TEXT_0    (GUI_ID_USER + 0x02)
#define ID_TEXT_1    (GUI_ID_USER + 0x03)
#define ID_TEXT_2    (GUI_ID_USER + 0x04)
#define ID_TEXT_3    (GUI_ID_USER + 0x05)
#define ID_CHECKBOX_0    (GUI_ID_USER + 0x06)
#define ID_BUTTON_1    (GUI_ID_USER + 0x07)
#define ID_BUTTON_2    (GUI_ID_USER + 0x08)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ShowWindow", ID_WINDOW_0, 0, 0, 497, 293, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "resetButton", ID_BUTTON_0, 20, 250, 120, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "titleText", ID_TEXT_0, 12, 12, 482, 28, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "timeText", ID_TEXT_1, 20, 126, 146, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "thetaText", ID_TEXT_2, 16, 57, 224, 31, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "gammaText", ID_TEXT_3, 14, 88, 227, 29, 0, 0x64, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 20, 144, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "singleButton", ID_BUTTON_1, 20, 175, 120, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "trackButton", ID_BUTTON_2, 20, 214, 121, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern __IO uint32_t nowTime;
// 刷新本界面显示
void show_reflesh(double theta, double gamma) {
    show_nowTime(nowTime);
    char buf[256]; 
    sprintf(buf, "theta = %f (deg)",theta);
    TEXT_SetText(WM_GetDialogItem(hWin_ShowWindow, ID_TEXT_2), buf);
    sprintf(buf, "gamma = %f (m)",gamma);
    TEXT_SetText(WM_GetDialogItem(hWin_ShowWindow, ID_TEXT_3), buf);
}

// 绘制位置

// 显示时间
void show_nowTime(u32 time) {
    char buf[256]; 
    sprintf(buf, "now time = %u ms", time);
    TEXT_SetText(WM_GetDialogItem(hWin_ShowWindow, ID_TEXT_1), buf);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'resetButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Reset");
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'titleText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "AUEDC 2022 | Sound Source Tracking System");
    //
    // Initialization of 'timeText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13_1);
    TEXT_SetText(hItem, "now time = ???");
    //
    // Initialization of 'thetaText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "theta = ??? (deg)");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'gammaText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "gamma = ??? (m)");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Light");
    //
    // Initialization of 'singleButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "Single");
    //
    // Initialization of 'trackButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_13_1);
    BUTTON_SetText(hItem, "Track");
    // USER START (Optionally insert additional code for further widget initialization)

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'resetButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'singleButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'trackButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateShowWindow
*/
WM_HWIN CreateShowWindow(void);
WM_HWIN CreateShowWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)

// void showPrint(const char *log)
// {
//     WM_HWIN hItem;
//     hItem = WM_GetDialogItem(hWin_ShowWindow, ID_MULTIEDIT_0);

//     int nowLen = MULTIEDIT_GetTextSize(hItem);

//     MULTIEDIT_SetCursorOffset(hItem,nowLen);
//     MULTIEDIT_AddText(hItem,log);

// }

// #include <stdarg.h>  
// void showPrintf(const char *fmt, ...)  {  
//     va_list va;  
//     char buf[1024];  
//     memset(buf, 0, 1024);  

//     va_start(va, fmt);  
//     vsprintf(buf, fmt, va);
//     va_end(va);  
      
//     showPrint( buf);  
// }  

// USER END

/*************************** End of file ****************************/
